export const globalContent = {
  logoUrl: "/milliondollarscoach_logo.jpeg",
  brandName: "PSYCHIC CHENNAI",
  email: "multi@milliondollarscoach.com",
  phone: "+1 8723473332",
  footerEmail: "multi@milliondollarscoach.com",
    footerPhone: "+1 8723473332",
  headerNavLinks: [
    { label: "Home", href: "/" },
    { label: "About", href: "/about" },
    { label: "Testimonials", href: "/testimonials" },
    { label: "Resources", href: "#home-discovery" },
    { label: "FAQs", href: "/faqs" },
    { label: "Survey", href: "/survey" },
    { label: "Contact", href: "#site-footer" },
  ],
  footer: {
      headline: "Clear Money Blocks, Create Multi-Million Success.",
  description: "Clear the subconscious patterns limiting your income and growth. Step into aligned action and build sustainable wealth expansion.",
    backgroundImageUrl: "/hero-workshop.svg",
    backgroundImageAlt: "Subtle spiritual silhouette background",
    connectLabel: "CONNECT",
    exploreLabel: "EXPLORE",
    contactLabel: "CONTACT",
    legalLabel: "LEGAL",
    copyright: "© 2026 Psychic India · Jothi Ramesh. All rights reserved.",
    exploreLinks: [
      { label: "Home", href: "/" },
      { label: "About", href: "/about" },
      { label: "Testimonials", href: "/testimonials" },
      { label: "FAQs", href: "/faqs" },
      { label: "Survey", href: "/survey" },
    ],
    legalLinks: [
      { label: "Privacy Policy", href: "/privacy-policy" },
      { label: "Terms & Conditions", href: "/terms" },
    ],
    socialLinks: [
      { label: "Instagram", href: "#" },
      { label: "LinkedIn", href: "#" },
      { label: "YouTube", href: "#" },
    ],
  },
} as const;
